### ISSUE TITLE
Example data files have same values in third column

### ISSUE THREAD

**Issue by zunzun** [latrop/GRCF#2]
All data points in the file example_1.data have the same value of 8.167 in the third column, and all data points in the file example_2.data have the same value of 9.14732 in the third column. Is this data correct?

**Comment by latrop** [comment]
This is just some mock synthetic data to test the package (I can't add the data for real galaxies yet due to the copyright issues). This examples were generated using analytical equations for bulge, disk, and halo, then some noise was added. The third column represents the noise level, which is the same for all data points of the file, therefore all lines contain the same value.

**Comment by zunzun** [comment]
I understand.  Thank you kindly for the explanation.
